import datetime
import zoneinfo

current_day = {
    'event_types': ['octopus_energy_electricity_current_day_rates'],
    'event_type': 'octopus_energy_electricity_current_day_rates', 'rates': [
        {'start': datetime.datetime(2025, 11, 6, 0, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 0, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.162435, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 0, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 1, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.16653, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 1, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 1, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.160965, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 1, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 2, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.158235, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 2, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 2, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.160125, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 2, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 3, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.15834, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 3, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 3, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.15435, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 3, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 4, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.15435, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 4, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 4, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.16275, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 4, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 5, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.16044, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 5, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 5, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.170625, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 5, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 6, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.16758, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 6, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 6, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.187425, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 6, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 7, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.187425, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 7, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 7, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.170415, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 7, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.200445, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 8, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 8, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.189, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 8, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.19026, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 9, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 9, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.17598, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 9, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 10, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.177765, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 10, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 10, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.176505, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 10, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 11, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.17598, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 11, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 11, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.18123, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 11, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 12, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.1806, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 12, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 12, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.18963, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 12, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 13, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.187005, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 13, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 13, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.21252, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 13, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 14, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.19488, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 14, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 14, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.222495, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 14, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 15, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.215775, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 15, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 15, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.22785, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 15, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.25536, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 16, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 16, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.380205, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 16, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 17, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.423255, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 17, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 17, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.402885, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 17, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 18, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.409815, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 18, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 18, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.398895, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 18, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 19, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.38745, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 19, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 19, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.23373, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 19, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 20, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.213885, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 20, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 20, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.20727, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 20, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 21, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.192465, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 21, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 21, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.188895, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 21, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 22, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.17199, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 22, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 22, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.176505, 'is_capped': False},
        {'start': datetime.datetime(2025, 11, 6, 22, 30, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'end': datetime.datetime(2025, 11, 6, 23, 0, tzinfo=zoneinfo.ZoneInfo(key='Europe/London')),
         'value_inc_vat': 0.169365, 'is_capped': False}], 'min_rate': 0.15435, 'max_rate': 0.423255,
    'average_rate': 0.21286696, 'mpan': '0000000000000', 'serial_number': '00000AAAAA',
    'tariff_code': 'E-1R-AGILE-24-10-01-A',
    'friendly_name': 'Current Day Rates Electricity'}

next_day = {
    "event_types": ["octopus_energy_electricity_next_day_rates"],
    "event_type": "octopus_energy_electricity_next_day_rates", "rates": [], "min_rate": None, "max_rate": None,
    "average_rate": 1, "mpan": "0000000000000", "serial_number": "00000AAAAA", "tariff_code": "E-1R-AGILE-24-10-01-A",
    "friendly_name": "Next Day Rates Electricity"}
